package com.recipeindex.app.ui.screens

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp
import com.recipeindex.app.data.entities.MealPlan
import com.recipeindex.app.data.entities.Recipe
import com.recipeindex.app.ui.components.AppDatePickerDialog
import com.recipeindex.app.utils.DebugConfig
import java.text.SimpleDateFormat
import java.util.*

/**
 * AddEditMealPlanScreen - Form for creating/editing meal plans
 *
 * Auto-saves when navigating back. Shows recipe picker bottom sheet.
 * Layout: Name, Date Range (optional), Recipe Picker, Notes
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddEditMealPlanScreen(
    mealPlan: MealPlan? = null,
    availableRecipes: List<Recipe>,
    onSave: (MealPlan) -> Unit,
    onCancel: () -> Unit,
    onAddToGroceryList: (() -> Unit)? = null
) {
    DebugConfig.debugLog(DebugConfig.Category.UI, "AddEditMealPlanScreen - editing: ${mealPlan != null}")

    var name by remember { mutableStateOf(mealPlan?.name ?: "") }
    var startDate by remember { mutableStateOf<Long?>(mealPlan?.startDate) }
    var endDate by remember { mutableStateOf<Long?>(mealPlan?.endDate) }
    var selectedRecipeIds by remember { mutableStateOf(mealPlan?.recipeIds ?: emptyList()) }
    var notes by remember { mutableStateOf(mealPlan?.notes ?: "") }
    var userHasEditedName by remember { mutableStateOf(mealPlan?.name?.isNotBlank() == true) }

    var showError by remember { mutableStateOf(false) }
    var errorMessage by remember { mutableStateOf("") }
    var showRecipePicker by remember { mutableStateOf(false) }
    var showDateRangePicker by remember { mutableStateOf(false) }
    var showMenu by remember { mutableStateOf(false) }

    // Auto-set name from dates if user hasn't manually edited it
    LaunchedEffect(startDate, endDate) {
        if (!userHasEditedName && (startDate != null || endDate != null)) {
            name = formatDateRange(startDate, endDate)
        }
    }

    // Auto-save logic when navigating back
    fun handleBack() {
        // Check if form has any meaningful content
        val hasContent = name.isNotBlank() || selectedRecipeIds.isNotEmpty()

        if (!hasContent) {
            // Empty form, just cancel
            onCancel()
            return
        }

        // Validate before saving
        when {
            name.isBlank() -> {
                errorMessage = "Meal plan name is required"
                showError = true
            }
            startDate != null && endDate != null && startDate!! > endDate!! -> {
                errorMessage = "Start date must be before or equal to end date"
                showError = true
            }
            else -> {
                // Valid data, auto-save
                val newPlan = MealPlan(
                    id = mealPlan?.id ?: 0,
                    name = name.trim(),
                    startDate = startDate,
                    endDate = endDate,
                    recipeIds = selectedRecipeIds,
                    tags = emptyList(), // Tags auto-generated by manager
                    notes = notes.ifBlank { null },
                    createdAt = mealPlan?.createdAt ?: System.currentTimeMillis(),
                    updatedAt = System.currentTimeMillis()
                )
                onSave(newPlan)
            }
        }
    }

    // Handle system back button
    BackHandler {
        handleBack()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(if (mealPlan != null) "Edit Meal Plan" else "Add Meal Plan") },
                navigationIcon = {
                    IconButton(onClick = { handleBack() }) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                },
                actions = {
                    // Show menu if callback is provided (both new and existing plans)
                    if (onAddToGroceryList != null) {
                        IconButton(onClick = { showMenu = true }) {
                            Icon(Icons.Default.MoreVert, contentDescription = "More options")
                        }

                        DropdownMenu(
                            expanded = showMenu,
                            onDismissRequest = { showMenu = false }
                        ) {
                            DropdownMenuItem(
                                text = { Text("Add to Grocery List") },
                                onClick = {
                                    showMenu = false
                                    onAddToGroceryList()
                                },
                                leadingIcon = {
                                    Icon(Icons.Default.ShoppingCart, contentDescription = null)
                                },
                                enabled = selectedRecipeIds.isNotEmpty()
                            )
                        }
                    }
                }
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .padding(16.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Name field with inline calendar button
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                verticalAlignment = Alignment.Top
            ) {
                OutlinedTextField(
                    value = name,
                    onValueChange = {
                        name = it
                        userHasEditedName = true
                    },
                    label = { Text("Name *") },
                    placeholder = { Text("e.g., Nov 18-22, Thanksgiving Dinner") },
                    modifier = Modifier.weight(1f),
                    singleLine = true,
                    isError = showError && name.isBlank(),
                    supportingText = {
                        if (startDate != null || endDate != null) {
                            Text(
                                text = formatDateRange(startDate, endDate),
                                style = MaterialTheme.typography.bodySmall
                            )
                        }
                    }
                )

                // Calendar icon button
                IconButton(
                    onClick = { showDateRangePicker = true },
                    modifier = Modifier.padding(top = 8.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.CalendarMonth,
                        contentDescription = "Select dates",
                        tint = if (startDate != null || endDate != null) {
                            MaterialTheme.colorScheme.primary
                        } else {
                            MaterialTheme.colorScheme.onSurfaceVariant
                        }
                    )
                }
            }

            Divider()

            // Recipes section
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = "Recipes (${selectedRecipeIds.size})",
                    style = MaterialTheme.typography.titleMedium
                )
                Button(onClick = { showRecipePicker = true }) {
                    Icon(Icons.Default.Add, contentDescription = null, modifier = Modifier.size(18.dp))
                    Spacer(modifier = Modifier.width(4.dp))
                    Text("Add Recipes")
                }
            }

            // Selected recipes list - enhanced cards with details
            if (selectedRecipeIds.isNotEmpty()) {
                val selectedRecipes = availableRecipes.filter { it.id in selectedRecipeIds }
                selectedRecipes.forEach { recipe ->
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp),
                        colors = CardDefaults.cardColors(
                            containerColor = MaterialTheme.colorScheme.surfaceVariant
                        )
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(12.dp)
                        ) {
                            // Title and remove button
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Text(
                                    text = recipe.title,
                                    style = MaterialTheme.typography.titleMedium,
                                    modifier = Modifier.weight(1f)
                                )
                                IconButton(
                                    onClick = {
                                        selectedRecipeIds = selectedRecipeIds.filter { it != recipe.id }
                                    }
                                ) {
                                    Icon(
                                        Icons.Default.Close,
                                        contentDescription = "Remove",
                                        tint = MaterialTheme.colorScheme.error
                                    )
                                }
                            }

                            // Servings and time info
                            if (recipe.prepTimeMinutes != null || recipe.cookTimeMinutes != null || recipe.servings > 0) {
                                Spacer(modifier = Modifier.height(4.dp))
                                Row(
                                    horizontalArrangement = Arrangement.spacedBy(12.dp)
                                ) {
                                    if (recipe.servings > 0) {
                                        Row(
                                            horizontalArrangement = Arrangement.spacedBy(4.dp),
                                            verticalAlignment = Alignment.CenterVertically
                                        ) {
                                            Icon(
                                                Icons.Default.Person,
                                                contentDescription = null,
                                                modifier = Modifier.size(16.dp),
                                                tint = MaterialTheme.colorScheme.onSurfaceVariant
                                            )
                                            Text(
                                                text = "${recipe.servings}",
                                                style = MaterialTheme.typography.bodySmall,
                                                color = MaterialTheme.colorScheme.onSurfaceVariant
                                            )
                                        }
                                    }

                                    val totalTime = (recipe.prepTimeMinutes ?: 0) + (recipe.cookTimeMinutes ?: 0)
                                    if (totalTime > 0) {
                                        Row(
                                            horizontalArrangement = Arrangement.spacedBy(4.dp),
                                            verticalAlignment = Alignment.CenterVertically
                                        ) {
                                            Icon(
                                                Icons.Default.Schedule,
                                                contentDescription = null,
                                                modifier = Modifier.size(16.dp),
                                                tint = MaterialTheme.colorScheme.onSurfaceVariant
                                            )
                                            Text(
                                                text = "${totalTime}m",
                                                style = MaterialTheme.typography.bodySmall,
                                                color = MaterialTheme.colorScheme.onSurfaceVariant
                                            )
                                        }
                                    }
                                }
                            }

                            // Tags
                            if (recipe.tags.isNotEmpty()) {
                                Spacer(modifier = Modifier.height(8.dp))
                                Row(
                                    horizontalArrangement = Arrangement.spacedBy(4.dp),
                                    modifier = Modifier.fillMaxWidth()
                                ) {
                                    recipe.tags.take(3).forEach { tag ->
                                        SuggestionChip(
                                            onClick = { },
                                            label = { Text(tag, style = MaterialTheme.typography.labelSmall) }
                                        )
                                    }
                                    if (recipe.tags.size > 3) {
                                        SuggestionChip(
                                            onClick = { },
                                            label = { Text("+${recipe.tags.size - 3}", style = MaterialTheme.typography.labelSmall) }
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                Text(
                    text = "No recipes added yet. Tap 'Add Recipes' to select.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(vertical = 8.dp)
                )
            }

            Divider()

            // Notes field
            OutlinedTextField(
                value = notes,
                onValueChange = { notes = it },
                label = { Text("Notes") },
                placeholder = { Text("Add any notes or special instructions") },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(120.dp),
                maxLines = 5
            )

            // Help text
            Text(
                text = "* Required fields",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
    }

    // Error dialog
    if (showError) {
        AlertDialog(
            onDismissRequest = { showError = false },
            title = { Text("Validation Error") },
            text = { Text(errorMessage) },
            confirmButton = {
                TextButton(onClick = { showError = false }) {
                    Text("OK")
                }
            }
        )
    }

    // Recipe picker bottom sheet
    if (showRecipePicker) {
        RecipePickerBottomSheet(
            availableRecipes = availableRecipes,
            selectedRecipeIds = selectedRecipeIds,
            onDismiss = { showRecipePicker = false },
            onRecipesSelected = { recipeIds ->
                selectedRecipeIds = recipeIds
                showRecipePicker = false
            }
        )
    }

    // Date range picker
    if (showDateRangePicker) {
        DateRangePickerDialog(
            initialStartDate = startDate,
            initialEndDate = endDate,
            onDatesSelected = { start, end ->
                startDate = start
                endDate = end
                showDateRangePicker = false
            },
            onClear = {
                startDate = null
                endDate = null
                showDateRangePicker = false
            },
            onDismiss = { showDateRangePicker = false }
        )
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun RecipePickerBottomSheet(
    availableRecipes: List<Recipe>,
    selectedRecipeIds: List<Long>,
    onDismiss: () -> Unit,
    onRecipesSelected: (List<Long>) -> Unit
) {
    var tempSelectedIds by remember { mutableStateOf(selectedRecipeIds) }
    var searchQuery by remember { mutableStateOf("") }
    var selectedTab by remember { mutableStateOf(1) } // 0 = Import, 1 = Existing (default to Existing)

    val filteredRecipes = if (searchQuery.isBlank()) {
        availableRecipes
    } else {
        availableRecipes.filter { it.title.contains(searchQuery, ignoreCase = true) }
    }

    // Full-screen dialog instead of bottom sheet
    BackHandler {
        onDismiss()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Add Recipes") },
                navigationIcon = {
                    IconButton(onClick = onDismiss) {
                        Icon(Icons.Default.Close, "Cancel")
                    }
                },
                actions = {
                    if (selectedTab == 1) {
                        TextButton(
                            onClick = { onRecipesSelected(tempSelectedIds) }
                        ) {
                            Text("Done (${tempSelectedIds.size})")
                        }
                    }
                }
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
        ) {
            // Tab Row
            TabRow(
                selectedTabIndex = selectedTab,
                modifier = Modifier.fillMaxWidth()
            ) {
                Tab(
                    selected = selectedTab == 0,
                    onClick = { selectedTab = 0 },
                    text = { Text("Import") },
                    icon = { Icon(Icons.Default.Add, contentDescription = null) }
                )
                Tab(
                    selected = selectedTab == 1,
                    onClick = { selectedTab = 1 },
                    text = { Text("Existing") },
                    icon = { Icon(Icons.Default.CheckCircle, contentDescription = null) }
                )
            }

            // Tab content
            when (selectedTab) {
                0 -> {
                    // Import tab - show import options
                    ImportRecipesTab(
                        modifier = Modifier.fillMaxSize(),
                        onImportComplete = {
                            // Switch to existing recipes tab to select the newly imported recipe
                            selectedTab = 1
                        }
                    )
                }
                1 -> {
                    // Existing recipes tab
                    Column(modifier = Modifier.fillMaxSize()) {
                        // Search field
                        OutlinedTextField(
                            value = searchQuery,
                            onValueChange = { searchQuery = it },
                placeholder = { Text("Search recipes...") },
                leadingIcon = { Icon(Icons.Default.Search, contentDescription = null) },
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp, vertical = 8.dp),
                singleLine = true
            )

            // Recipe grid (2 per row)
            LazyVerticalGrid(
                columns = GridCells.Fixed(2),
                modifier = Modifier.fillMaxSize(),
                contentPadding = PaddingValues(16.dp),
                horizontalArrangement = Arrangement.spacedBy(12.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                items(filteredRecipes, key = { it.id }) { recipe ->
                    val isSelected = recipe.id in tempSelectedIds

                    Card(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(140.dp),
                        onClick = {
                            tempSelectedIds = if (isSelected) {
                                tempSelectedIds.filter { it != recipe.id }
                            } else {
                                tempSelectedIds + recipe.id
                            }
                        },
                        colors = CardDefaults.cardColors(
                            containerColor = if (isSelected) {
                                MaterialTheme.colorScheme.primaryContainer
                            } else {
                                MaterialTheme.colorScheme.surfaceVariant
                            }
                        )
                    ) {
                        Box(modifier = Modifier.fillMaxSize()) {
                            Column(
                                modifier = Modifier
                                    .fillMaxSize()
                                    .padding(12.dp),
                                verticalArrangement = Arrangement.SpaceBetween
                            ) {
                                Text(
                                    text = recipe.title,
                                    style = MaterialTheme.typography.bodyMedium,
                                    maxLines = 3
                                )
                                Column {
                                    Text(
                                        text = "${recipe.servings} servings",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = MaterialTheme.colorScheme.onSurfaceVariant
                                    )
                                    val totalTime = (recipe.prepTimeMinutes ?: 0) + (recipe.cookTimeMinutes ?: 0)
                                    if (totalTime > 0) {
                                        Text(
                                            text = "${totalTime}m",
                                            style = MaterialTheme.typography.labelSmall,
                                            color = MaterialTheme.colorScheme.onSurfaceVariant
                                        )
                                    }
                                }
                            }
                            if (isSelected) {
                                Icon(
                                    Icons.Default.CheckCircle,
                                    contentDescription = "Selected",
                                    tint = MaterialTheme.colorScheme.primary,
                                    modifier = Modifier
                                        .align(Alignment.TopEnd)
                                        .padding(8.dp)
                                        .size(24.dp)
                                )
                            }
                        }
                    }
                }
            }
                    }
                }
            }
        }
    }
}

/**
 * Import Recipes Tab - Shows import options (URL/PDF/Photo)
 */
@Composable
private fun ImportRecipesTab(
    modifier: Modifier = Modifier,
    onImportComplete: () -> Unit
) {
    Column(
        modifier = modifier
            .padding(16.dp)
            .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text(
            text = "Import New Recipe",
            style = MaterialTheme.typography.headlineSmall,
            color = MaterialTheme.colorScheme.onSurface
        )

        Text(
            text = "Import a recipe to add to this meal plan",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Spacer(modifier = Modifier.height(8.dp))

        // Import options
        ImportSourceCard(
            icon = Icons.Default.InsertLink,
            title = "From URL",
            description = "Import from recipe websites",
            onClick = { /* TODO: Navigate to import URL screen */ }
        )

        ImportSourceCard(
            icon = Icons.Default.PictureAsPdf,
            title = "From PDF",
            description = "Import from PDF files",
            onClick = { /* TODO: Navigate to PDF import */ },
            enabled = false
        )

        ImportSourceCard(
            icon = Icons.Default.CameraAlt,
            title = "From Photo",
            description = "Import using camera or gallery",
            onClick = { /* TODO: Navigate to photo import */ },
            enabled = false
        )
    }
}

/**
 * Import source card for meal plan recipe import
 */
@Composable
private fun ImportSourceCard(
    icon: ImageVector,
    title: String,
    description: String,
    onClick: () -> Unit,
    enabled: Boolean = true
) {
    Card(
        onClick = onClick,
        enabled = enabled,
        modifier = Modifier.fillMaxWidth()
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            horizontalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Icon(
                imageVector = icon,
                contentDescription = null,
                modifier = Modifier.size(48.dp),
                tint = if (enabled) {
                    MaterialTheme.colorScheme.primary
                } else {
                    MaterialTheme.colorScheme.onSurface.copy(alpha = 0.38f)
                }
            )

            Column(
                modifier = Modifier.weight(1f),
                verticalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                Text(
                    text = title,
                    style = MaterialTheme.typography.titleMedium,
                    color = if (enabled) {
                        MaterialTheme.colorScheme.onSurface
                    } else {
                        MaterialTheme.colorScheme.onSurface.copy(alpha = 0.38f)
                    }
                )

                Text(
                    text = description,
                    style = MaterialTheme.typography.bodyMedium,
                    color = if (enabled) {
                        MaterialTheme.colorScheme.onSurfaceVariant
                    } else {
                        MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.38f)
                    }
                )

                if (!enabled) {
                    Text(
                        text = "Coming soon",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.primary.copy(alpha = 0.6f)
                    )
                }
            }
        }
    }
}

private fun formatDate(timestamp: Long): String {
    val dateFormat = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())
    return dateFormat.format(Date(timestamp))
}

private fun formatDateRange(startDate: Long?, endDate: Long?): String {
    if (startDate == null && endDate == null) return ""

    if (startDate != null && endDate != null) {
        val start = Date(startDate)
        val end = Date(endDate)
        val cal = Calendar.getInstance()

        cal.time = start
        val startMonth = SimpleDateFormat("MMM", Locale.getDefault()).format(start)
        val startDay = cal.get(Calendar.DAY_OF_MONTH)
        val startYear = cal.get(Calendar.YEAR)

        cal.time = end
        val endMonth = SimpleDateFormat("MMM", Locale.getDefault()).format(end)
        val endDay = cal.get(Calendar.DAY_OF_MONTH)
        val endYear = cal.get(Calendar.YEAR)

        // Same month and year: "Nov 18-22"
        if (startMonth == endMonth && startYear == endYear) {
            return "$startMonth $startDay-$endDay"
        }

        // Same year, different months: "Nov 28 - Dec 5"
        if (startYear == endYear) {
            return "$startMonth $startDay - $endMonth $endDay"
        }

        // Different years: "Dec 28 - Jan 2"
        return "$startMonth $startDay - $endMonth $endDay"
    }

    // Only one date set
    if (startDate != null) {
        return "From ${SimpleDateFormat("MMM dd", Locale.getDefault()).format(Date(startDate))}"
    }

    return "Until ${SimpleDateFormat("MMM dd", Locale.getDefault()).format(Date(endDate!!))}"
}

/**
 * Date Range Picker Dialog - allows selecting single date or date range
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun DateRangePickerDialog(
    initialStartDate: Long?,
    initialEndDate: Long?,
    onDatesSelected: (startDate: Long?, endDate: Long?) -> Unit,
    onClear: () -> Unit,
    onDismiss: () -> Unit
) {
    val dateRangePickerState = rememberDateRangePickerState(
        initialSelectedStartDateMillis = initialStartDate,
        initialSelectedEndDateMillis = initialEndDate
    )

    DatePickerDialog(
        onDismissRequest = onDismiss,
        confirmButton = {
            TextButton(
                onClick = {
                    onDatesSelected(
                        dateRangePickerState.selectedStartDateMillis,
                        dateRangePickerState.selectedEndDateMillis
                    )
                }
            ) {
                Text("OK")
            }
        },
        dismissButton = {
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                if (initialStartDate != null || initialEndDate != null) {
                    TextButton(onClick = onClear) {
                        Text("Clear")
                    }
                }
                TextButton(onClick = onDismiss) {
                    Text("Cancel")
                }
            }
        }
    ) {
        DateRangePicker(
            state = dateRangePickerState,
            title = {
                Text(
                    text = "Select date range (optional)",
                    modifier = Modifier.padding(16.dp)
                )
            },
            headline = {
                val start = dateRangePickerState.selectedStartDateMillis
                val end = dateRangePickerState.selectedEndDateMillis
                Text(
                    text = when {
                        start != null && end != null -> "${formatDate(start)} - ${formatDate(end)}"
                        start != null -> "From ${formatDate(start)}"
                        else -> "Select dates"
                    },
                    modifier = Modifier.padding(horizontal = 16.dp)
                )
            }
        )
    }
}
