package com.recipeindex.app.ui.screens

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.recipeindex.app.data.entities.MealPlan
import com.recipeindex.app.data.entities.Recipe
import com.recipeindex.app.utils.DebugConfig
import java.text.SimpleDateFormat
import java.util.*

/**
 * AddEditMealPlanScreen - Form for creating/editing meal plans
 *
 * Auto-saves when navigating back. Shows recipe picker bottom sheet.
 * Layout: Name, Date Range (optional), Recipe Picker, Notes
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddEditMealPlanScreen(
    mealPlan: MealPlan? = null,
    availableRecipes: List<Recipe>,
    onSave: (MealPlan) -> Unit,
    onCancel: () -> Unit
) {
    DebugConfig.debugLog(DebugConfig.Category.UI, "AddEditMealPlanScreen - editing: ${mealPlan != null}")

    var name by remember { mutableStateOf(mealPlan?.name ?: "") }
    var startDate by remember { mutableStateOf<Long?>(mealPlan?.startDate) }
    var endDate by remember { mutableStateOf<Long?>(mealPlan?.endDate) }
    var selectedRecipeIds by remember { mutableStateOf(mealPlan?.recipeIds ?: emptyList()) }
    var notes by remember { mutableStateOf(mealPlan?.notes ?: "") }

    var showError by remember { mutableStateOf(false) }
    var errorMessage by remember { mutableStateOf("") }
    var showRecipePicker by remember { mutableStateOf(false) }
    var showStartDatePicker by remember { mutableStateOf(false) }
    var showEndDatePicker by remember { mutableStateOf(false) }

    // Auto-save logic when navigating back
    fun handleBack() {
        // Check if form has any meaningful content
        val hasContent = name.isNotBlank() || selectedRecipeIds.isNotEmpty()

        if (!hasContent) {
            // Empty form, just cancel
            onCancel()
            return
        }

        // Validate before saving
        when {
            name.isBlank() -> {
                errorMessage = "Meal plan name is required"
                showError = true
            }
            startDate != null && endDate != null && startDate!! > endDate!! -> {
                errorMessage = "Start date must be before or equal to end date"
                showError = true
            }
            else -> {
                // Valid data, auto-save
                val newPlan = MealPlan(
                    id = mealPlan?.id ?: 0,
                    name = name.trim(),
                    startDate = startDate,
                    endDate = endDate,
                    recipeIds = selectedRecipeIds,
                    tags = emptyList(), // Tags auto-generated by manager
                    notes = notes.ifBlank { null },
                    createdAt = mealPlan?.createdAt ?: System.currentTimeMillis(),
                    updatedAt = System.currentTimeMillis()
                )
                onSave(newPlan)
            }
        }
    }

    // Handle system back button
    BackHandler {
        handleBack()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(if (mealPlan != null) "Edit Meal Plan" else "Add Meal Plan") },
                navigationIcon = {
                    IconButton(onClick = { handleBack() }) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                }
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .padding(16.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Name field
            OutlinedTextField(
                value = name,
                onValueChange = { name = it },
                label = { Text("Name *") },
                placeholder = { Text("e.g., Nov 18-22, Thanksgiving Dinner") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                isError = showError && name.isBlank()
            )

            // Date range section
            Text(
                text = "Date Range (Optional)",
                style = MaterialTheme.typography.titleMedium
            )

            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                OutlinedButton(
                    onClick = { showStartDatePicker = true },
                    modifier = Modifier.weight(1f)
                ) {
                    Column(horizontalAlignment = Alignment.CenterHorizontally) {
                        Text("Start Date", style = MaterialTheme.typography.labelSmall)
                        Text(
                            text = startDate?.let { formatDate(it) } ?: "Not set",
                            style = MaterialTheme.typography.bodyMedium
                        )
                    }
                }

                OutlinedButton(
                    onClick = { showEndDatePicker = true },
                    modifier = Modifier.weight(1f)
                ) {
                    Column(horizontalAlignment = Alignment.CenterHorizontally) {
                        Text("End Date", style = MaterialTheme.typography.labelSmall)
                        Text(
                            text = endDate?.let { formatDate(it) } ?: "Not set",
                            style = MaterialTheme.typography.bodyMedium
                        )
                    }
                }
            }

            if (startDate != null || endDate != null) {
                TextButton(
                    onClick = {
                        startDate = null
                        endDate = null
                    }
                ) {
                    Icon(Icons.Default.Clear, contentDescription = null, modifier = Modifier.size(18.dp))
                    Spacer(modifier = Modifier.width(4.dp))
                    Text("Clear Dates")
                }
            }

            Divider()

            // Recipes section
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = "Recipes (${selectedRecipeIds.size})",
                    style = MaterialTheme.typography.titleMedium
                )
                Button(onClick = { showRecipePicker = true }) {
                    Icon(Icons.Default.Add, contentDescription = null, modifier = Modifier.size(18.dp))
                    Spacer(modifier = Modifier.width(4.dp))
                    Text("Add Recipes")
                }
            }

            // Selected recipes list
            if (selectedRecipeIds.isNotEmpty()) {
                val selectedRecipes = availableRecipes.filter { it.id in selectedRecipeIds }
                selectedRecipes.forEach { recipe ->
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(12.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                text = recipe.title,
                                style = MaterialTheme.typography.bodyLarge,
                                modifier = Modifier.weight(1f)
                            )
                            IconButton(
                                onClick = {
                                    selectedRecipeIds = selectedRecipeIds.filter { it != recipe.id }
                                }
                            ) {
                                Icon(
                                    Icons.Default.Close,
                                    contentDescription = "Remove",
                                    tint = MaterialTheme.colorScheme.error
                                )
                            }
                        }
                    }
                }
            } else {
                Text(
                    text = "No recipes added yet. Tap 'Add Recipes' to select.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(vertical = 8.dp)
                )
            }

            Divider()

            // Notes field
            OutlinedTextField(
                value = notes,
                onValueChange = { notes = it },
                label = { Text("Notes") },
                placeholder = { Text("Add any notes or special instructions") },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(120.dp),
                maxLines = 5
            )

            // Help text
            Text(
                text = "* Required fields",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
    }

    // Error dialog
    if (showError) {
        AlertDialog(
            onDismissRequest = { showError = false },
            title = { Text("Validation Error") },
            text = { Text(errorMessage) },
            confirmButton = {
                TextButton(onClick = { showError = false }) {
                    Text("OK")
                }
            }
        )
    }

    // Recipe picker bottom sheet
    if (showRecipePicker) {
        RecipePickerBottomSheet(
            availableRecipes = availableRecipes,
            selectedRecipeIds = selectedRecipeIds,
            onDismiss = { showRecipePicker = false },
            onRecipesSelected = { recipeIds ->
                selectedRecipeIds = recipeIds
                showRecipePicker = false
            }
        )
    }

    // Date pickers (placeholder - will be replaced with proper Material3 date picker when available)
    if (showStartDatePicker) {
        SimpleDatePickerDialog(
            initialDate = startDate,
            onDateSelected = { selectedDate ->
                startDate = selectedDate
                showStartDatePicker = false
            },
            onDismiss = { showStartDatePicker = false }
        )
    }

    if (showEndDatePicker) {
        SimpleDatePickerDialog(
            initialDate = endDate,
            onDateSelected = { selectedDate ->
                endDate = selectedDate
                showEndDatePicker = false
            },
            onDismiss = { showEndDatePicker = false }
        )
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun RecipePickerBottomSheet(
    availableRecipes: List<Recipe>,
    selectedRecipeIds: List<Long>,
    onDismiss: () -> Unit,
    onRecipesSelected: (List<Long>) -> Unit
) {
    var tempSelectedIds by remember { mutableStateOf(selectedRecipeIds) }
    var searchQuery by remember { mutableStateOf("") }

    val filteredRecipes = if (searchQuery.isBlank()) {
        availableRecipes
    } else {
        availableRecipes.filter { it.title.contains(searchQuery, ignoreCase = true) }
    }

    ModalBottomSheet(
        onDismissRequest = onDismiss
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp)
        ) {
            Text(
                text = "Select Recipes",
                style = MaterialTheme.typography.titleLarge,
                modifier = Modifier.padding(bottom = 16.dp)
            )

            // Search field
            OutlinedTextField(
                value = searchQuery,
                onValueChange = { searchQuery = it },
                placeholder = { Text("Search recipes...") },
                leadingIcon = { Icon(Icons.Default.Search, contentDescription = null) },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true
            )

            Spacer(modifier = Modifier.height(16.dp))

            // Recipe list
            LazyColumn(
                modifier = Modifier
                    .fillMaxWidth()
                    .weight(1f, fill = false)
                    .heightIn(max = 400.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                items(filteredRecipes, key = { it.id }) { recipe ->
                    val isSelected = recipe.id in tempSelectedIds

                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        onClick = {
                            tempSelectedIds = if (isSelected) {
                                tempSelectedIds.filter { it != recipe.id }
                            } else {
                                tempSelectedIds + recipe.id
                            }
                        },
                        colors = CardDefaults.cardColors(
                            containerColor = if (isSelected) {
                                MaterialTheme.colorScheme.primaryContainer
                            } else {
                                MaterialTheme.colorScheme.surface
                            }
                        )
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(16.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column(modifier = Modifier.weight(1f)) {
                                Text(
                                    text = recipe.title,
                                    style = MaterialTheme.typography.bodyLarge
                                )
                                Text(
                                    text = "${recipe.servings} servings",
                                    style = MaterialTheme.typography.bodySmall,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant
                                )
                            }
                            if (isSelected) {
                                Icon(
                                    Icons.Default.CheckCircle,
                                    contentDescription = "Selected",
                                    tint = MaterialTheme.colorScheme.primary
                                )
                            }
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Action buttons
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                OutlinedButton(
                    onClick = onDismiss,
                    modifier = Modifier.weight(1f)
                ) {
                    Text("Cancel")
                }
                Button(
                    onClick = { onRecipesSelected(tempSelectedIds) },
                    modifier = Modifier.weight(1f)
                ) {
                    Text("Done (${tempSelectedIds.size})")
                }
            }
        }
    }
}

@Composable
private fun SimpleDatePickerDialog(
    initialDate: Long?,
    onDateSelected: (Long) -> Unit,
    onDismiss: () -> Unit
) {
    // Simple placeholder date picker
    // In a real app, use Material3 DatePickerDialog when available or a library
    val calendar = Calendar.getInstance()
    if (initialDate != null) {
        calendar.timeInMillis = initialDate
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Select Date") },
        text = {
            Column {
                Text("Date: ${formatDate(calendar.timeInMillis)}")
                Spacer(modifier = Modifier.height(8.dp))
                Text(
                    "Note: Full date picker coming soon. For now, set to today.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
        },
        confirmButton = {
            TextButton(onClick = { onDateSelected(calendar.timeInMillis) }) {
                Text("Set Today")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel")
            }
        }
    )
}

private fun formatDate(timestamp: Long): String {
    val dateFormat = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())
    return dateFormat.format(Date(timestamp))
}
